config/routes.rb
Rails.application.routes.draw do

  namespace :crawler do
    resources :website_types
  end
  namespace :crawler do
    get '/' => 'base#index'

    resources :websites

    resources :plans do
      collection do
      end
      member do
        get :flush_page
        get :today_finish

        get :exce
        post :exce
      end
    end
    resources :menus do
      collection do

      end
      member do
        get :move
      end
    end
    resources :works do
      collection do
        get :tj
        post :tj
        get :wj
        post :wj
        get :handle
        post :handle
      end
      member do
      end
    end
  end

  # 城市四级联动
  resources :streets
  resources :cities
  resources :provinces

  # resources :crawler_sys, :only => [:index,:show] do

  mount HelloApi, at: '/api/'
  mount VueApi, at: '/vueapi'
  mount GrapeSwaggerRails::Engine, at: '/apidoc'

  root 'welcome#index'
end

app/models/crawler.rb
module Crawler
  def self.table_name_prefix
    'crawler_'
  end
end

app/models/crawler/menu.rb
class Crawler::Menu < ApplicationRecord

  CONTROLLERS = {plans:'计划',menus:'菜单',works:'岗位'}
  ACTIONS = {new:'新建',edit:'修改',index:'首页',exec:'执行',test:'测试',tj:'统计',wj:'挖掘',handle:'处理'}

  def parent
    Crawler::Menu.where("id = '#{parent_id}'").first
  end
  def owner
    parent
  end
  def childs
    children
  end
  def children
    Crawler::Menu.where("parent_id = '#{id}'")
  end

  # 生成菜单链接
  def url
    str = "/"
    str += "#{namespace}" if !namespace.blank?
    str += "/#{controller}" if !controller.blank?
    str += "/#{action}" if !action.blank?
    str
  end

  # 生成导航
  def navs
    menus = [self]
    loop do
      parent_menu = menus.first.owner
      break if parent_menu.nil? or parent_menu == menus.first
      menus.unshift(parent_menu)
    end
    menus
  end

  # 移动菜单的排序
  def self.move a, type
    case type
      when '顶'
        Crawler::Menu.find_by_location(1).update location:a.location
        a.update location:1
      when '上'
        Crawler::Menu.find_by_location(a.location.to_i-1).update location:a.location
        a.update location:(a.location-1)
      when '下'
        Crawler::Menu.find_by_location(a.location.to_i+1).update location:a.location
        a.update location:(a.location+1)
      when '底'
        last = Crawler::Menu.all.order(:location).last
        a_l = a.location
        a.update location:last.location
        last.update location:a_l
    end
  end


end

app/models/crawler/website.rb
class Crawler::Website < ApplicationRecord
  has_many :works
  has_many :plans
  belongs_to :website_type
end

app/models/crawler/website_type.rb
class Crawler::WebsiteType < ApplicationRecord
  has_many :websites

end

app/controllers/crawler/base_controller.rb
class Crawler::BaseController < ApplicationController
  before_action :check_current_user
  before_action :get_current_menus

  layout :set_layout

  def index

  end

  def check_current_user

  end

  def get_current_menus
    @all_menus = Crawler::Menu.all.order :location
    @index_menu = Crawler::Menu.find_by_name('系统首页')
    # @menus = @index_menu.children#.map{|m| m}.unshift(@index_menu)
    @menus = @all_menus

    controller = params[:controller].split('/')[1]
    if params[:action]=='index'
      action = ''
    else
      if @all_menus.map(&:action).include?(params[:action])
        action = params[:action]
      else
        action = ''
      end
    end
    @current_menu = Crawler::Menu.where("controller = '#{controller}' and action = '#{action}'").first
    @current_menu = @index_menu if !@current_menu
    @navs = @current_menu.navs
  end

  def set_layout
    if !params[:layout].blank?
      session[:layout] = params[:layout]
    else
      session[:layout] = session[:layout].nil? ? 'crawler' : session[:layout]
    end
    session[:layout]
  end
  
end

app/controllers/crawler/menus_controller.rb
class Crawler::MenusController < Crawler::BaseController
  before_action :set_crawler_menu, only: [:move, :copy, :show, :edit, :update, :destroy]

  # GET /crawler/menus
  # GET /crawler/menus.json
  def index
    @crawler_menus = Crawler::Menu.all.order :location
  end

  # GET /crawler/menus/1
  # GET /crawler/menus/1.json
  def show
  end

  # GET /crawler/menus/new
  def new
    @crawler_menu = Crawler::Menu.new
  end

  def move
    Crawler::Menu.move @crawler_menu, params[:move] if params[:move]
    redirect_to action: :index
  end

  # GET /crawler/menus/1/edit
  def edit
  end

  # POST /crawler/menus
  # POST /crawler/menus.json
  def create
    @crawler_menu = Crawler::Menu.new(crawler_menu_params)

    respond_to do |format|
      if @crawler_menu.save
        format.html { redirect_to @crawler_menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_menu }
      else
        format.html { render :new }
        format.json { render json: @crawler_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/menus/1
  # PATCH/PUT /crawler/menus/1.json
  def update
    respond_to do |format|
      if @crawler_menu.update(crawler_menu_params)
        format.html { redirect_to @crawler_menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_menu }
      else
        format.html { render :edit }
        format.json { render json: @crawler_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/menus/1
  # DELETE /crawler/menus/1.json
  def destroy
    @crawler_menu.destroy
    respond_to do |format|
      format.html { redirect_to crawler_menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_menu
      @crawler_menu = Crawler::Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_menu_params
      params.require(:crawler_menu).permit(:name, :namespace, :controller, :action, :note, :parent_id)
    end
end

app/controllers/crawler/plans_controller.rb
class Crawler::PlansController < Crawler::BaseController
  before_action :set_crawler_plan, only: [:today_finish, :flush_page, :exce, :auto_exce, :show, :edit, :update, :destroy]

  @@exec_histroy = {}
  # GET /crawler/plans
  # GET /crawler/plans.json
  def index
    # params[:q] = {website_id_eq:params[:website_id]} if params[:website_id]
    @q = Crawler::Plan.includes(:website).ransack(params[:q])
    @count = @q.result.size
    @per = params[:per].blank? ? 50 : params[:per].to_i
    @pagecount = @count % @per > 0 ? @count / @per + 1 : @count
    @crawler_plans = @q.result.order(:website_id).page(params[:page]).per(@per)
  end


  # 执行采集
  def exce
    ip = request.env['HTTP_X_FORWARDED_FOR'].present? ? request.env['HTTP_X_FORWARDED_FOR'] : request.remote_ip
    puts "ip:#{ip}, count:  #{@@exec_histroy[ip].to_s}"
    @@exec_histroy[ip] = {page:0,count:0} if @@exec_histroy[ip].nil?
    if @@exec_histroy[ip][:page] > 100 or @@exec_histroy[ip][:count] > 10
      @msg = "#{ip}:每天只能尝试采集10次,或100页,您已超过了限制,请明天再来"
      return
    end
    @plans = Crawler::Plan.all
    a = params[:page_a]
    b = params[:page_b]
    if a.blank? or b.blank?
      @msg = "手动采集必须填写页码a-b"
      return
    else
      a = a.to_i
      b = b.to_i
      if b < a
        @msg = "b页不能小于a"
        return
      end

      results = @crawler_plan.exce_works(a, b, params[:include_work_name], params[:filter_work_name], params[:save_flag])
      @works = results[:works]
      time = results[:time]
      data_count = @works.map{|k,v| v.size}.sum
      if results[:ok]
        @msg = "执行完成,共用时 #{time} 秒, 共对#{b-a+1}页进行了采集, #{data_count}条"
        @@exec_histroy[ip][:page] += (b-a+1)
      else
        @msg = "执行中断,止于第#{results[:error_page]}页,共用时 #{time} 秒, 共对#{results[:error_page].to_i-a+1}页进行了采集, 处理数据#{data_count}条
                错误原因:#{results[:error][:title]},<br/>栈:#{results[:error][:contents]}"
        @@exec_histroy[ip][:page] += (results[:error_page].to_i-a+1)
      end
    end
    @@exec_histroy[ip][:count] += 1
  end

  def flush_page
    @crawler_plan.flush_page
    redirect_to action: :index
  end

  def today_finish
    @crawler_plan.today_finish
    redirect_to action: :index
  end

  # GET /crawler/plans/1
  # GET /crawler/plans/1.json
  def show
  end

  # GET /crawler/plans/new
  def new
    @crawler_plan = Crawler::Plan.new
  end

  # GET /crawler/plans/1/edit
  def edit
  end

  # POST /crawler/plans
  # POST /crawler/plans.json
  def create
    @crawler_plan = Crawler::Plan.new(crawler_plan_params)

    respond_to do |format|
      if @crawler_plan.save
        format.html { redirect_to @crawler_plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_plan }
      else
        format.html { render :new }
        format.json { render json: @crawler_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/plans/1
  # PATCH/PUT /crawler/plans/1.json
  def update
    respond_to do |format|
      if @crawler_plan.update(crawler_plan_params)
        format.html { redirect_to @crawler_plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_plan }
      else
        format.html { render :edit }
        format.json { render json: @crawler_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/plans/1
  # DELETE /crawler/plans/1.json
  def destroy
    @crawler_plan.destroy
    respond_to do |format|
      format.html { redirect_to crawler_plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_plan
      @crawler_plan = Crawler::Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_plan_params
      params.require(:crawler_plan).permit(:website_id, :source, :name, :url, :page, :note)
    end
end

app/controllers/crawler/website_types_controller.rb
class Crawler::WebsiteTypesController < Crawler::BaseController
  before_action :set_crawler_website_type, only: [:show, :edit, :update, :destroy]

  # GET /crawler/website_types
  # GET /crawler/website_types.json
  def index
    @crawler_website_types = Crawler::WebsiteType.all
  end

  # GET /crawler/website_types/1
  # GET /crawler/website_types/1.json
  def show
  end

  # GET /crawler/website_types/new
  def new
    @crawler_website_type = Crawler::WebsiteType.new
  end

  # GET /crawler/website_types/1/edit
  def edit
  end

  # POST /crawler/website_types
  # POST /crawler/website_types.json
  def create
    @crawler_website_type = Crawler::WebsiteType.new(crawler_website_type_params)

    respond_to do |format|
      if @crawler_website_type.save
        format.html { redirect_to @crawler_website_type, notice: 'Website type was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_website_type }
      else
        format.html { render :new }
        format.json { render json: @crawler_website_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/website_types/1
  # PATCH/PUT /crawler/website_types/1.json
  def update
    respond_to do |format|
      if @crawler_website_type.update(crawler_website_type_params)
        format.html { redirect_to @crawler_website_type, notice: 'Website type was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_website_type }
      else
        format.html { render :edit }
        format.json { render json: @crawler_website_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/website_types/1
  # DELETE /crawler/website_types/1.json
  def destroy
    @crawler_website_type.destroy
    respond_to do |format|
      format.html { redirect_to crawler_website_types_url, notice: 'Website type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_website_type
      @crawler_website_type = Crawler::WebsiteType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_website_type_params
      params.require(:crawler_website_type).permit(:name, :note)
    end
end

app/controllers/crawler/websites_controller.rb
class Crawler::WebsitesController < Crawler::BaseController
  before_action :set_crawler_website, only: [:show, :edit, :update, :destroy]

  # GET /crawler/websites
  # GET /crawler/websites.json
  def index
    @crawler_websites = Crawler::Website.includes(:website_type)
  end

  # GET /crawler/websites/1
  # GET /crawler/websites/1.json
  def show
  end

  # GET /crawler/websites/new
  def new
    @crawler_website = Crawler::Website.new
  end

  # GET /crawler/websites/1/edit
  def edit
  end

  # POST /crawler/websites
  # POST /crawler/websites.json
  def create
    @crawler_website = Crawler::Website.new(crawler_website_params)

    respond_to do |format|
      if @crawler_website.save
        format.html { redirect_to @crawler_website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_website }
      else
        format.html { render :new }
        format.json { render json: @crawler_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/websites/1
  # PATCH/PUT /crawler/websites/1.json
  def update
    respond_to do |format|
      if @crawler_website.update(crawler_website_params)
        format.html { redirect_to @crawler_website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_website }
      else
        format.html { render :edit }
        format.json { render json: @crawler_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/websites/1
  # DELETE /crawler/websites/1.json
  def destroy
    @crawler_website.destroy
    respond_to do |format|
      format.html { redirect_to crawler_websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_website
      @crawler_website = Crawler::Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_website_params
      params.require(:crawler_website).permit(:name, :index_url, :website_type_id, :note)
    end
end

app/helpers/crawler/base_helper.rb
module Crawler::BaseHelper
end

app/helpers/crawler/core_helper.rb
module Crawler::CoreHelper
end

app/helpers/crawler/menus_helper.rb
module Crawler::MenusHelper
end

app/helpers/crawler/plans_helper.rb
module Crawler::PlansHelper
end

app/helpers/crawler/website_types_helper.rb
module Crawler::WebsiteTypesHelper
end

app/helpers/crawler/websites_helper.rb
module Crawler::WebsitesHelper
end

app/helpers/crawler/works_helper.rb
module Crawler::WorksHelper
end

app/helpers/crawler_helper.rb
module CrawlerHelper
end

app/views/crawler/works/_form.html.erb
<%= form_with(model: crawler_work, local: true) do |form| %>
  <% if crawler_work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crawler_work.errors.count, "error") %> prohibited this crawler_work from being saved:</h2>

      <ul>
      <% crawler_work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :crawler_work_name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :crawler_work_url %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, id: :crawler_work_text %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name, id: :crawler_work_company_name %>
  </div>

  <div class="field">
    <%= form.label :company_url %>
    <%= form.text_field :company_url, id: :crawler_work_company_url %>
  </div>

  <div class="field">
    <%= form.label :price_scope %>
    <%= form.text_field :price_scope, id: :crawler_work_price_scope %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :crawler_work_address %>
  </div>

  <div class="field">
    <%= form.label :price_min %>
    <%= form.number_field :price_min, id: :crawler_work_price_min %>
  </div>

  <div class="field">
    <%= form.label :price_max %>
    <%= form.number_field :price_max, id: :crawler_work_price_max %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :crawler_work_city %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.number_field :company_id, id: :crawler_work_company_id %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :crawler_work_category %>
  </div>

  <div class="field">
    <%= form.label :website_id %>
    <%= form.text_field :website_id, id: :crawler_work_website_id %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note, id: :crawler_work_note %>
  </div>

  <div class="field">
    <%= form.label :send_time %>
    <%= form.text_field :send_time, id: :crawler_work_send_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crawler/works/_work_table_list.html.erb
<div class="table-responsive">
  <table class="table table-hover table-condensed">
    <thead>
    <tr>
      <th width="4%"></th>
      <th width="20%">名称</th>
      <th width="20%">公司</th>
      <th>wkhash</th>
      <th>cphash</th>
      <th>城市</th>
      <th>add</th>
      <th>来源</th>
      <th>更新?</th>
      <th>最低</th>
      <th>最高</th>
      <th>时间</th>
      <th><%= check_box_tag :check_qx, 'check_qx', false %></th>
    </tr>
    </thead>
    <tbody>
    <% works.each_with_index do |w, i| %>
        <tr>
          <td><%= i+1 %></td>
          <td><%= link_to w.name, w.url, target:'view_window' %></td>
          <td><%= link_to w.company_name, w.company_url, target:'view_window' %></td>
          <td><%= w.work_hash %></td>
          <td><%= w.company_hash %></td>
          <td><%= w.city %></td>
          <td><%= w.address %></td>
          <td><%= w.website.name %></td>
          <td><%= w.tracking %></td>
          <td><%= w.price_min %></td>
          <td><%= w.price_max %></td>
          <td><%= w.send_time %></td>
          <td><%= check_box_tag :w_id, w.id, false %></td>
        </tr>
    <% end %>
    </tbody>

  </table>
</div>

<script>
    $('#check_qx').click(function(){
        if(this.checked){
            $('input[name=w_id]').each(function(){
                this.checked = true;
            });
        }else{
            $('input[name=w_id]').each(function(){
                this.checked = false;
            });
        }
    });
//  var all_checked = function(e){
//      alert($(e).checked);
//      cs = $('input[type="w_id"]');
//      for(var i=0;i<cs.length;i++){
//          cs.eq(i).attr('checked',true);
//      }
//  }

</script>

app/views/crawler/works/edit.html.erb
<h1>Editing Crawler Work</h1>

<%= render 'form', crawler_work: @crawler_work, btn_name: '修改' %>

<%= link_to 'Show', @crawler_work %> |
<%= link_to 'Back', crawler_works_path %>

app/views/crawler/works/handle.html.erb
数据处理,过滤,分类

app/views/crawler/works/index.html.erb
<div class="alert alert-success alert-dismissable text-center">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <%= "共搜索到结果#{@count}条,#{@pagecount}页" %>
</div>

<div class="row clearfix">
  <div class="col-md-12 column">
  <%= search_form_for @q, class:'form-horizontal', method:'get' do |f| %>
      work_hash<%= f.search_field :work_hash_eq %>
      日期<%= f.search_field :send_time_eq  %><br/>
      职位包含<%= f.search_field :name_cont %>
        职位不包含<%= f.search_field :name_not_cont %><br/>

        公司包含<%= f.search_field :company_name_cont %>
        公司不包含<%= f.search_field :company_name_not_cont %><br/>

        最低工资小于<%= f.search_field :price_min_lt %>
        最低工资大于<%= f.search_field :price_min_gt %><br/>

        最高工资小于<%= f.search_field :price_max_lt %>
        最高工资大于<%= f.search_field :price_max_gt %><br/>

        按字段排序<%= text_field_tag :order, @order %>
        <!--是否更新?<%#= f.select :tracking_eq, ['yes','no'], { :include_blank => true } %><br/>-->

      城市<%= f.select :address_cont, Crawler::Work.citys, { :include_blank => true } %>
      所属计划<%= f.select :plan_id_eq, Crawler::Plan.all.map{|p| [p.name,p.id]}, { :include_blank => true } %>
      来源<%= f.select :website_id_eq, Crawler::Website.all.map{|w| [w.name,w.id]}, { :include_blank => true } %><br/>
        每页显示条数<%= number_field_tag :per, @per %><%= f.submit "搜索",class:'btn btn-default' %>

  <% end %>
  </div>
</div>



<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#panel-1" data-toggle="tab">表单</a></li>
    <li><a href="#panel-2" data-toggle="tab">处理<span class="badge"></span></a></li>
    <li><a href="#panel-3" data-toggle="tab">其它其它<span class="badge"></span></a></li>
    <li><a href="#panel-4" data-toggle="tab">图形<span class="badge"></span></a></li>
    <li class="dropdown pull-right">
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
        操作 <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li>
          <a href="javascript:handle('tracking_all');">全部保存</a>
        </li>
        <li>
          <a href="javascript:handle('del_all');" data-confirm="确定要全部删除吗?真的确认?">全部删除</a>
        </li>
        <li class="divider"><br></li>
        <li>
          <a href="#">分割线</a>
        </li>
      </ul>
    </li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="panel-1">
      <div class="gd h500">
        <%= render :partial => '/crawler/works/work_table_list', :locals => { :works => @works } %>
      </div>
      <div>
        <%= paginate @works %>
      </div>
    </div>
    <div class="tab-pane" id="panel-2">
      处理
    </div>
    <div class="tab-pane" id="panel-3">
      其它
    </div>
    <div class="tab-pane" id="panel-4">
      <canvas id="line" width="400" height="400"  class="bo-a"></canvas>
      <canvas id="bar" width="400" height="400"  class="bo-a"></canvas>
      <canvas id="pie" width="400" height="400" class="bo-a"></canvas>
      <canvas id="pie2" width="400" height="400" class="bo-a"></canvas>
    </div>
  </div>
</div>

<script>
  var handle = function(handle){
      w_ids = [];
      $('input[name=w_id]').each(function(){
          if(this.checked){
              w_ids.push(this.value);
          }
      })
      $.ajax({
          url:'/crawler/works/handle.json',
          method:'post',
          data:{
              w_ids:w_ids,
              handle:handle,
          },
          success:function(data){
              if(data.ok){

              }else{

              }
              alert(data.msg);
          }
      });
  }
</script>

app/views/crawler/works/new.html.erb
<h1>New Crawler Work</h1>

<%= render 'form', crawler_work: @crawler_work %>

<%= link_to 'Back', crawler_works_path %>

app/views/crawler/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @crawler_work.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @crawler_work.url %>
</p>

<p>
  <strong>Text:</strong>
  <%= @crawler_work.text %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @crawler_work.company_name %>
</p>

<p>
  <strong>Company url:</strong>
  <%= @crawler_work.company_url %>
</p>

<p>
  <strong>Price scope:</strong>
  <%= @crawler_work.price_scope %>
</p>

<p>
  <strong>Address:</strong>
  <%= @crawler_work.address %>
</p>

<p>
  <strong>Price min:</strong>
  <%= @crawler_work.price_min %>
</p>

<p>
  <strong>Price max:</strong>
  <%= @crawler_work.price_max %>
</p>

<p>
  <strong>City:</strong>
  <%= @crawler_work.city %>
</p>

<p>
  <strong>Company:</strong>
  <%= @crawler_work.company_id %>
</p>

<p>
  <strong>Category:</strong>
  <%= @crawler_work.category %>
</p>

<p>
  <strong>Website:</strong>
  <%= @crawler_work.website_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @crawler_work.note %>
</p>

<p>
  <strong>Send time:</strong>
  <%= @crawler_work.send_time %>
</p>

<%= link_to 'Edit', edit_crawler_work_path(@crawler_work) %> |
<%= link_to 'Back', crawler_works_path %>

app/views/crawler/works/wj.html.erb
URL深度挖掘