config/routes.rb
Rails.application.routes.draw do

  namespace :crawler do
    resources :website_types
  end
  namespace :crawler do
    get '/' => 'base#index'

    resources :websites

    resources :plans do
      collection do
      end
      member do
        get :flush_page
        get :today_finish

        get :exce
        post :exce
      end
    end
    resources :menus do
      collection do

      end
      member do
        get :move
      end
    end
    resources :works do
      collection do
        get :tj
        post :tj
        get :wj
        post :wj
        get :handle
        post :handle
      end
      member do
      end
    end
  end

  # 城市四级联动
  resources :streets
  resources :cities
  resources :provinces

  # resources :crawler_sys, :only => [:index,:show] do

  mount HelloApi, at: '/api/'
  mount VueApi, at: '/vueapi'
  mount GrapeSwaggerRails::Engine, at: '/apidoc'

  root 'welcome#index'
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :city

  def owner
    city
  end

end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController
  before_action :set_street, only: [:show, :edit, :update, :destroy]

  # GET /streets
  # GET /streets.json
  def index
    @streets = Street.all
  end

  # GET /streets/1
  # GET /streets/1.json
  def show
  end

  # GET /streets/new
  def new
    @street = Street.new
  end

  # GET /streets/1/edit
  def edit
  end

  # POST /streets
  # POST /streets.json
  def create
    @street = Street.new(street_params)

    respond_to do |format|
      if @street.save
        format.html { redirect_to @street, notice: 'Street was successfully created.' }
        format.json { render :show, status: :created, location: @street }
      else
        format.html { render :new }
        format.json { render json: @street.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streets/1
  # PATCH/PUT /streets/1.json
  def update
    respond_to do |format|
      if @street.update(street_params)
        format.html { redirect_to @street, notice: 'Street was successfully updated.' }
        format.json { render :show, status: :ok, location: @street }
      else
        format.html { render :edit }
        format.json { render json: @street.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streets/1
  # DELETE /streets/1.json
  def destroy
    @street.destroy
    respond_to do |format|
      format.html { redirect_to streets_url, notice: 'Street was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_street
      @street = Street.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def street_params
      params.require(:street).permit(:city_id, :name, :code)
    end
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/streets/_form.html.erb
<%= form_with(model: street, local: true) do |form| %>
  <% if street.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(street.errors.count, "error") %> prohibited this street from being saved:</h2>

      <ul>
      <% street.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.number_field :city_id, id: :street_city_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :street_name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :street_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/streets/edit.html.erb
<h1>Editing Street</h1>

<%= render 'form', street: @street %>

<%= link_to 'Show', @street %> |
<%= link_to 'Back', streets_path %>

app/views/streets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Streets</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Name</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @streets.each do |street| %>
      <tr>
        <td><%= street.city_id %></td>
        <td><%= street.name %></td>
        <td><%= street.code %></td>
        <td><%= link_to 'Show', street %></td>
        <td><%= link_to 'Edit', edit_street_path(street) %></td>
        <td><%= link_to 'Destroy', street, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Street', new_street_path %>

app/views/streets/new.html.erb
<h1>New Street</h1>

<%= render 'form', street: @street %>

<%= link_to 'Back', streets_path %>

app/views/streets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @street.city_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @street.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @street.code %>
</p>

<%= link_to 'Edit', edit_street_path(@street) %> |
<%= link_to 'Back', streets_path %>