config/routes.rb
Rails.application.routes.draw do

  namespace :crawler do
    resources :website_types
  end
  namespace :crawler do
    get '/' => 'base#index'

    resources :websites

    resources :plans do
      collection do
      end
      member do
        get :flush_page
        get :today_finish

        get :exce
        post :exce
      end
    end
    resources :menus do
      collection do

      end
      member do
        get :move
      end
    end
    resources :works do
      collection do
        get :tj
        post :tj
        get :wj
        post :wj
        get :handle
        post :handle
      end
      member do
      end
    end
  end

  # 城市四级联动
  resources :streets
  resources :cities
  resources :provinces

  # resources :crawler_sys, :only => [:index,:show] do

  mount HelloApi, at: '/api/'
  mount VueApi, at: '/vueapi'
  mount GrapeSwaggerRails::Engine, at: '/apidoc'

  root 'welcome#index'
end

app/models/crawler.rb
module Crawler
  def self.table_name_prefix
    'crawler_'
  end
end

app/models/crawler/menu.rb
class Crawler::Menu < ApplicationRecord

  CONTROLLERS = {plans:'计划',menus:'菜单',works:'岗位'}
  ACTIONS = {new:'新建',edit:'修改',index:'首页',exec:'执行',test:'测试',tj:'统计',wj:'挖掘',handle:'处理'}

  def parent
    Crawler::Menu.where("id = '#{parent_id}'").first
  end
  def owner
    parent
  end
  def childs
    children
  end
  def children
    Crawler::Menu.where("parent_id = '#{id}'")
  end

  # 生成菜单链接
  def url
    str = "/"
    str += "#{namespace}" if !namespace.blank?
    str += "/#{controller}" if !controller.blank?
    str += "/#{action}" if !action.blank?
    str
  end

  # 生成导航
  def navs
    menus = [self]
    loop do
      parent_menu = menus.first.owner
      break if parent_menu.nil? or parent_menu == menus.first
      menus.unshift(parent_menu)
    end
    menus
  end

  # 移动菜单的排序
  def self.move a, type
    case type
      when '顶'
        Crawler::Menu.find_by_location(1).update location:a.location
        a.update location:1
      when '上'
        Crawler::Menu.find_by_location(a.location.to_i-1).update location:a.location
        a.update location:(a.location-1)
      when '下'
        Crawler::Menu.find_by_location(a.location.to_i+1).update location:a.location
        a.update location:(a.location+1)
      when '底'
        last = Crawler::Menu.all.order(:location).last
        a_l = a.location
        a.update location:last.location
        last.update location:a_l
    end
  end


end

app/models/crawler/website.rb
class Crawler::Website < ApplicationRecord
  has_many :works
  has_many :plans
  belongs_to :website_type
end

app/models/crawler/website_type.rb
class Crawler::WebsiteType < ApplicationRecord
  has_many :websites

end

app/controllers/crawler/base_controller.rb
class Crawler::BaseController < ApplicationController
  before_action :check_current_user
  before_action :get_current_menus

  layout :set_layout

  def index

  end

  def check_current_user

  end

  def get_current_menus
    @all_menus = Crawler::Menu.all.order :location
    @index_menu = Crawler::Menu.find_by_name('系统首页')
    # @menus = @index_menu.children#.map{|m| m}.unshift(@index_menu)
    @menus = @all_menus

    controller = params[:controller].split('/')[1]
    if params[:action]=='index'
      action = ''
    else
      if @all_menus.map(&:action).include?(params[:action])
        action = params[:action]
      else
        action = ''
      end
    end
    @current_menu = Crawler::Menu.where("controller = '#{controller}' and action = '#{action}'").first
    @current_menu = @index_menu if !@current_menu
    @navs = @current_menu.navs
  end

  def set_layout
    if !params[:layout].blank?
      session[:layout] = params[:layout]
    else
      session[:layout] = session[:layout].nil? ? 'crawler' : session[:layout]
    end
    session[:layout]
  end
  
end

app/controllers/crawler/menus_controller.rb
class Crawler::MenusController < Crawler::BaseController
  before_action :set_crawler_menu, only: [:move, :copy, :show, :edit, :update, :destroy]

  # GET /crawler/menus
  # GET /crawler/menus.json
  def index
    @crawler_menus = Crawler::Menu.all.order :location
  end

  # GET /crawler/menus/1
  # GET /crawler/menus/1.json
  def show
  end

  # GET /crawler/menus/new
  def new
    @crawler_menu = Crawler::Menu.new
  end

  def move
    Crawler::Menu.move @crawler_menu, params[:move] if params[:move]
    redirect_to action: :index
  end

  # GET /crawler/menus/1/edit
  def edit
  end

  # POST /crawler/menus
  # POST /crawler/menus.json
  def create
    @crawler_menu = Crawler::Menu.new(crawler_menu_params)

    respond_to do |format|
      if @crawler_menu.save
        format.html { redirect_to @crawler_menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_menu }
      else
        format.html { render :new }
        format.json { render json: @crawler_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/menus/1
  # PATCH/PUT /crawler/menus/1.json
  def update
    respond_to do |format|
      if @crawler_menu.update(crawler_menu_params)
        format.html { redirect_to @crawler_menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_menu }
      else
        format.html { render :edit }
        format.json { render json: @crawler_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/menus/1
  # DELETE /crawler/menus/1.json
  def destroy
    @crawler_menu.destroy
    respond_to do |format|
      format.html { redirect_to crawler_menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_menu
      @crawler_menu = Crawler::Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_menu_params
      params.require(:crawler_menu).permit(:name, :namespace, :controller, :action, :note, :parent_id)
    end
end

app/controllers/crawler/plans_controller.rb
class Crawler::PlansController < Crawler::BaseController
  before_action :set_crawler_plan, only: [:today_finish, :flush_page, :exce, :auto_exce, :show, :edit, :update, :destroy]

  @@exec_histroy = {}
  # GET /crawler/plans
  # GET /crawler/plans.json
  def index
    # params[:q] = {website_id_eq:params[:website_id]} if params[:website_id]
    @q = Crawler::Plan.includes(:website).ransack(params[:q])
    @count = @q.result.size
    @per = params[:per].blank? ? 50 : params[:per].to_i
    @pagecount = @count % @per > 0 ? @count / @per + 1 : @count
    @crawler_plans = @q.result.order(:website_id).page(params[:page]).per(@per)
  end


  # 执行采集
  def exce
    ip = request.env['HTTP_X_FORWARDED_FOR'].present? ? request.env['HTTP_X_FORWARDED_FOR'] : request.remote_ip
    puts "ip:#{ip}, count:  #{@@exec_histroy[ip].to_s}"
    @@exec_histroy[ip] = {page:0,count:0} if @@exec_histroy[ip].nil?
    if @@exec_histroy[ip][:page] > 100 or @@exec_histroy[ip][:count] > 10
      @msg = "#{ip}:每天只能尝试采集10次,或100页,您已超过了限制,请明天再来"
      return
    end
    @plans = Crawler::Plan.all
    a = params[:page_a]
    b = params[:page_b]
    if a.blank? or b.blank?
      @msg = "手动采集必须填写页码a-b"
      return
    else
      a = a.to_i
      b = b.to_i
      if b < a
        @msg = "b页不能小于a"
        return
      end

      results = @crawler_plan.exce_works(a, b, params[:include_work_name], params[:filter_work_name], params[:save_flag])
      @works = results[:works]
      time = results[:time]
      data_count = @works.map{|k,v| v.size}.sum
      if results[:ok]
        @msg = "执行完成,共用时 #{time} 秒, 共对#{b-a+1}页进行了采集, #{data_count}条"
        @@exec_histroy[ip][:page] += (b-a+1)
      else
        @msg = "执行中断,止于第#{results[:error_page]}页,共用时 #{time} 秒, 共对#{results[:error_page].to_i-a+1}页进行了采集, 处理数据#{data_count}条
                错误原因:#{results[:error][:title]},<br/>栈:#{results[:error][:contents]}"
        @@exec_histroy[ip][:page] += (results[:error_page].to_i-a+1)
      end
    end
    @@exec_histroy[ip][:count] += 1
  end

  def flush_page
    @crawler_plan.flush_page
    redirect_to action: :index
  end

  def today_finish
    @crawler_plan.today_finish
    redirect_to action: :index
  end

  # GET /crawler/plans/1
  # GET /crawler/plans/1.json
  def show
  end

  # GET /crawler/plans/new
  def new
    @crawler_plan = Crawler::Plan.new
  end

  # GET /crawler/plans/1/edit
  def edit
  end

  # POST /crawler/plans
  # POST /crawler/plans.json
  def create
    @crawler_plan = Crawler::Plan.new(crawler_plan_params)

    respond_to do |format|
      if @crawler_plan.save
        format.html { redirect_to @crawler_plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_plan }
      else
        format.html { render :new }
        format.json { render json: @crawler_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/plans/1
  # PATCH/PUT /crawler/plans/1.json
  def update
    respond_to do |format|
      if @crawler_plan.update(crawler_plan_params)
        format.html { redirect_to @crawler_plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_plan }
      else
        format.html { render :edit }
        format.json { render json: @crawler_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/plans/1
  # DELETE /crawler/plans/1.json
  def destroy
    @crawler_plan.destroy
    respond_to do |format|
      format.html { redirect_to crawler_plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_plan
      @crawler_plan = Crawler::Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_plan_params
      params.require(:crawler_plan).permit(:website_id, :source, :name, :url, :page, :note)
    end
end

app/controllers/crawler/website_types_controller.rb
class Crawler::WebsiteTypesController < Crawler::BaseController
  before_action :set_crawler_website_type, only: [:show, :edit, :update, :destroy]

  # GET /crawler/website_types
  # GET /crawler/website_types.json
  def index
    @crawler_website_types = Crawler::WebsiteType.all
  end

  # GET /crawler/website_types/1
  # GET /crawler/website_types/1.json
  def show
  end

  # GET /crawler/website_types/new
  def new
    @crawler_website_type = Crawler::WebsiteType.new
  end

  # GET /crawler/website_types/1/edit
  def edit
  end

  # POST /crawler/website_types
  # POST /crawler/website_types.json
  def create
    @crawler_website_type = Crawler::WebsiteType.new(crawler_website_type_params)

    respond_to do |format|
      if @crawler_website_type.save
        format.html { redirect_to @crawler_website_type, notice: 'Website type was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_website_type }
      else
        format.html { render :new }
        format.json { render json: @crawler_website_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/website_types/1
  # PATCH/PUT /crawler/website_types/1.json
  def update
    respond_to do |format|
      if @crawler_website_type.update(crawler_website_type_params)
        format.html { redirect_to @crawler_website_type, notice: 'Website type was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_website_type }
      else
        format.html { render :edit }
        format.json { render json: @crawler_website_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/website_types/1
  # DELETE /crawler/website_types/1.json
  def destroy
    @crawler_website_type.destroy
    respond_to do |format|
      format.html { redirect_to crawler_website_types_url, notice: 'Website type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_website_type
      @crawler_website_type = Crawler::WebsiteType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_website_type_params
      params.require(:crawler_website_type).permit(:name, :note)
    end
end

app/controllers/crawler/websites_controller.rb
class Crawler::WebsitesController < Crawler::BaseController
  before_action :set_crawler_website, only: [:show, :edit, :update, :destroy]

  # GET /crawler/websites
  # GET /crawler/websites.json
  def index
    @crawler_websites = Crawler::Website.includes(:website_type)
  end

  # GET /crawler/websites/1
  # GET /crawler/websites/1.json
  def show
  end

  # GET /crawler/websites/new
  def new
    @crawler_website = Crawler::Website.new
  end

  # GET /crawler/websites/1/edit
  def edit
  end

  # POST /crawler/websites
  # POST /crawler/websites.json
  def create
    @crawler_website = Crawler::Website.new(crawler_website_params)

    respond_to do |format|
      if @crawler_website.save
        format.html { redirect_to @crawler_website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @crawler_website }
      else
        format.html { render :new }
        format.json { render json: @crawler_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crawler/websites/1
  # PATCH/PUT /crawler/websites/1.json
  def update
    respond_to do |format|
      if @crawler_website.update(crawler_website_params)
        format.html { redirect_to @crawler_website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @crawler_website }
      else
        format.html { render :edit }
        format.json { render json: @crawler_website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crawler/websites/1
  # DELETE /crawler/websites/1.json
  def destroy
    @crawler_website.destroy
    respond_to do |format|
      format.html { redirect_to crawler_websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crawler_website
      @crawler_website = Crawler::Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crawler_website_params
      params.require(:crawler_website).permit(:name, :index_url, :website_type_id, :note)
    end
end

app/helpers/crawler/base_helper.rb
module Crawler::BaseHelper
end

app/helpers/crawler/core_helper.rb
module Crawler::CoreHelper
end

app/helpers/crawler/menus_helper.rb
module Crawler::MenusHelper
end

app/helpers/crawler/plans_helper.rb
module Crawler::PlansHelper
end

app/helpers/crawler/website_types_helper.rb
module Crawler::WebsiteTypesHelper
end

app/helpers/crawler/websites_helper.rb
module Crawler::WebsitesHelper
end

app/helpers/crawler/works_helper.rb
module Crawler::WorksHelper
end

app/helpers/crawler_helper.rb
module CrawlerHelper
end

app/views/crawler/plans/_form.html.erb
<%= form_for crawler_plan, html:{class:"form-horizontal"} do |form| %>

    <% if crawler_plan.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(crawler_plan.errors.count, "error") %> 保存失败,原因如下:</h2>

          <ul>
            <% crawler_plan.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= form.label '来源站点',class:'col-sm-2 control-label', for:'source' %>
      <div class="col-sm-10">
        <%= form.select :website_id, Crawler::Website.all.map{|w| [w.name, w.id]}, class:'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label '计划名称',class:'col-sm-2 control-label', for:'name' %>
      <div class="col-sm-10">
        <%= form.text_field :name, id: :name, class:'w_100', placeholder: '给URL条件取名称,例:"全国-标题(销售)-工资(1~2万)-发布日期(近一月)-公司性质(民营~创业~上市)"' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label '备注',class:'col-sm-2 control-label', for:'note' %>
      <div class="col-sm-10">
        <%= form.text_area :note, id: :note, style: 'width:100%;height:100px;', placeholder: '输入备注,比如说这个采集计划的目的,未来将如何分析这些数据的策略等' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label '目标URL',class:'col-sm-2 control-label', for:'url' %>
      <div class="col-sm-10">
        <%= form.text_area :url, id: :url, style: 'width:100%;height:160px;', placeholder: '要抓取的页面URL,例:http://search.51job.com/list/000000,000000,0000,00,3,07%252C08%252C09%252C10%252C11,%25E9%25A6%2596%25E5%25B8%25AD%25E6%258A%2580%25E6%259C%25AF%25E5%25AE%2598,2,PAGE.html?lang=c&stype=1&postchannel=0000&workyear=02%2C03%2C04&cotype=03%2C04%2C05%2C10%2C11&degreefrom=03%2C04%2C05%2C06&jobterm=99&companysize=99&lonlat=0%2C0&radius=-1&ord_field=0&confirmdate=9&fromType=&dibiaoid=0&address=&line=&specialarea=00&from=&welfare=' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label '总页数',class:'col-sm-2 control-label', for:'page' %>
      <div class="col-sm-10">
        <%= form.number_field :page, id: :page %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= form.submit submit_name,class:'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/crawler/plans/edit.html.erb
<div class="page-header text-center">
  <h1>修改数据采集计划</h1>
  <p class="lead">
  </p>
</div>
<%= render 'form', crawler_plan: @crawler_plan, submit_name: "修改" %>

<%= link_to '显示', @crawler_plan %> |
<%= link_to '返回', crawler_plans_path %>

app/views/crawler/plans/exce.html.erb
<div class="page-header ">
  <p class="lead">
    采集计划:<%= link_to @crawler_plan.name, crawler_plan_path(@crawler_plan) %>&nbsp;&nbsp;
    目标站点:<%= link_to @crawler_plan.website.name, @crawler_plan.website.index_url %><br/>
  </p>
</div>

<div>
  <%= form_tag exce_crawler_plan_path, method:'post', class:"form-horizontal" do %>
      <div class="form-group">
        <label class='col-sm-2 control-label' for="page_a">页码</label>
        <div class="col-sm-10">
          <%= text_field_tag :page_a, params[:page_a], placeholder:'开始页码(必填)' %>
          <%= text_field_tag :page_b, params[:page_b], placeholder:'截止页码(必填)' %>
        </div>
      </div>
      <div class="form-group">
        <label class='col-sm-2 control-label' for="filter_work_name">过滤</label>
        <div class="col-sm-10">
          <%= text_field_tag :filter_work_name, params[:filter_work_name], placeholder:'从标题中过滤关键字' %>
          <%= text_field_tag :include_work_name, params[:include_work_name], placeholder:'标题中必须出现关键字' %>
        </div>
      </div>
      <div class="form-group">
        <label class='col-sm-2 control-label' for="stop_count"></label>
        <div class="col-sm-8">
          <%= submit_tag "手动采集",class:'btn btn-default' %>
          直接保存?<%= check_box_tag :save_flag, 'yes', true %>
        </div>
      </div>

  <% end %>
</div>

<!--结果页签-->
<div class="text-center">
  <% if @works %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= @msg %>
      </div>
      <div class="tabbable">
        <ul class="nav nav-tabs">
          <li class="active">
            <a href="#panel-1" data-toggle="tab">首次采集<span class="badge"><%= @works[:success].size %></span></a>
          </li>
          <li>
            <a href="#panel-2" data-toggle="tab">更新<span class="badge"><%= @works[:update].size %></span></a>
          </li>
          <li>
            <a href="#panel-3" data-toggle="tab">重复的(未保存)<span class="badge"><%= @works[:exist].size %></span></a>
          </li>
          <li>
            <a href="#panel-4" data-toggle="tab">保存失败<span class="badge"><%= @works[:fail].size %></span></a>
          </li>
          <li>
            <a href="#panel-5" data-toggle="tab">过滤的<span class="badge"><%= @works[:filter].size %></span></a>
          </li>
          <li>
            <a href="#panel-6" data-toggle="tab">未执行保存的<span class="badge"><%= @works[:no_save].size %></span></a>
          </li>
          <li class="dropdown pull-right">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
              操作 <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="#">全部保存</a>
              </li>
              <li>
                <a href="#">全部放弃</a>
              </li>
              <li class="divider"><br></li>
              <li>
                <a href="#">分割线</a>
              </li>
            </ul>
          </li>
        </ul>

        <div class="tab-content">
          <div class="tab-pane active" id="panel-1">
            <div class="gd h500"><%= render :partial => '/crawler/works/work_table_list', :locals => { :works => @works[:success].first(50) } %></div>
          </div>
          <div class="tab-pane" id="panel-2">
            <div class="gd h500"><%= render :partial => '/crawler/works/work_table_list', :locals => { :works => @works[:update].first(50) } %></div>
          </div>
          <div class="tab-pane" id="panel-3">
            <div class="gd h500"><%= render :partial => '/crawler/works/work_table_list', :locals => { :works => @works[:exist].first(50) } %></div>
          </div>
          <div class="tab-pane" id="panel-4">
            <div class="gd h500"><%= render :partial => '/crawler/works/work_table_list', :locals => { :works => @works[:fail].first(50) } %></div>
          </div>
          <div class="tab-pane" id="panel-5">
            <div class="gd h500"><%= render :partial => '/crawler/works/work_table_list', :locals => { :works => @works[:filter].first(50) } %></div>
          </div>
          <div class="tab-pane" id="panel-6">
            <div class="gd h500"><%= render :partial => '/crawler/works/work_table_list', :locals => { :works => @works[:no_save].first(50) } %></div>
          </div>
        </div>
      </div>
  <% else %>
      <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= @msg %>
      </div>
  <% end %>
</div>

app/views/crawler/plans/index.html.erb
<div class="page-header text-center">
  <p class="lead">
    所有数据采集计划列表
  </p>

</div>


<div class="row clearfix">
  <div class="col-md-12 column">
    <%= search_form_for @q, class:'form-horizontal', method:'get' do |f| %>
        名称<%= f.search_field :name_cont %>
        来源<%= f.select :website_id_eq, Crawler::Website.all.map{|w| [w.name,w.id]}, { :include_blank => true } %>
        <%= f.submit "搜索",class:'btn btn-default' %>

    <% end %>
  </div>
</div>

<!--计划首页-显示所有计划-->
<div class="table-responsive">
  <table class="table table-hover table-condensed">
    <div class="fr">
      <!--<button onclick="flush_plans()">全部刷新</button>-->
      <%= link_to '刷新计划', '/crawler/plans/flush' %>
    </div>
    <thead>
    <tr>
      <th>序号</th>
      <th>名称</th>
      <th>总页数</th>
      <th>来源</th>
      <th colspan="3">操作</th>
    </tr>
    </thead>
    <tbody>
    <% @crawler_plans.each_with_index do |p, i| %>
        <tr>
          <td><%= i+1 %></td>
          <td><%= link_to p.name, p.http_url, target:'view_window' %></td>
          <td><%= p.page %></td>
          <td><%= link_to p.website.name, p.website.index_url, target:'view_window' %></td>
          <td><%= p.today_finish? ? '完成' : (link_to '采集', exce_crawler_plan_path(p)) %></td>
          <td><%= p.today_finish? ? '' : (link_to '今日已完成', today_finish_crawler_plan_path(p)) %></td>
          <td><%= link_to '修改', edit_crawler_plan_path(p) %></td>
          <td><%= link_to '刷新页数', flush_page_crawler_plan_path(p) %></td>
          <td><%= link_to '删除', p, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>

  </table>

  <div>
    <%= paginate @crawler_plans %>
  </div>
</div>


<script>
  var flush_plans = function(){
      $.ajax({
          url:'/crawler/plans/flush',
          method:'get',
          data:{},
          success:function(data){
              if(data.ok){

              }else{
                  alert(data.msg);
              }
          }
      })
  }
</script>

app/views/crawler/plans/new.html.erb
<div class="page-header text-center">
  <p class="lead">
    新建采集计划
  </p>
</div>

<%= render 'form', crawler_plan: @crawler_plan, submit_name: '创建' %>

<%= link_to '返回', crawler_plans_path %>

app/views/crawler/plans/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <p class="lead">
    采集计划:<%= @crawler_plan.name %><br/>
    目标站点:<%= link_to @crawler_plan.website.name, @crawler_plan.website.index_url %><br/>
    目标URL:<br/><%= link_to @crawler_plan.url, @crawler_plan.url.split('PAGE').join('1') %><br/>
    备注:<%= @crawler_plan.note %><br/>
  </p>
</div>

<%= link_to '去采集', exce_crawler_plan_path(@crawler_plan), class:'btn btn-default' %>

<%= link_to '修改', edit_crawler_plan_path(@crawler_plan), class:'btn btn-default' %>
<%= link_to '返回', crawler_plans_path, class:'btn btn-default' %>