config/routes.rb
Rails.application.routes.draw do

  namespace :crawler do
    resources :website_types
  end
  namespace :crawler do
    get '/' => 'base#index'

    resources :websites

    resources :plans do
      collection do
      end
      member do
        get :flush_page
        get :today_finish

        get :exce
        post :exce
      end
    end
    resources :menus do
      collection do

      end
      member do
        get :move
      end
    end
    resources :works do
      collection do
        get :tj
        post :tj
        get :wj
        post :wj
        get :handle
        post :handle
      end
      member do
      end
    end
  end

  # 城市四级联动
  resources :streets
  resources :cities
  resources :provinces

  # resources :crawler_sys, :only => [:index,:show] do

  mount HelloApi, at: '/api/'
  mount VueApi, at: '/vueapi'
  mount GrapeSwaggerRails::Engine, at: '/apidoc'

  root 'welcome#index'
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :citys

  def childs
    citys
  end

  def parent_citys
    citys.where("parent_id is null")
  end



end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: 'Province was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name, :code)
    end
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/provinces/_form.html.erb
<%= form_with(model: province, local: true) do |form| %>
  <% if province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :province_name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :province_code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<div id="" class="w_100">

  <div class="">

  </div>


  <div class="pos-rel w_80 pd10 mid">
    <p id="notice" class="text-center"><%= notice %></p>
    <h1 class="text-center mb15">省份 | <%= link_to '添加', new_province_path %></h1>

    <% @provinces.each_with_index do |province, i| %>
        <div class="fl w_20 mb15">
          <%= link_to province.name, province %>
        </div>
    <% end %>
  </div>

</div>

app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @province.code %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>